//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ENTIDADES;
    
    public partial class BancoEntities : DbContext
    {
        public BancoEntities()
            : base("name=BancoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta_ahorro> Cuenta_ahorro { get; set; }
        public virtual DbSet<Historial_Credito> Historial_Credito { get; set; }
        public virtual DbSet<Historial_Prestamos> Historial_Prestamos { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarjetas_Credito> Tarjetas_Credito { get; set; }
        public virtual DbSet<Transacciones> Transacciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<CvClientes> CvClientes { get; set; }
        public virtual DbSet<CvCuentas> CvCuentas { get; set; }
        public virtual DbSet<CvPrestamos> CvPrestamos { get; set; }
        public virtual DbSet<CvTarjetas> CvTarjetas { get; set; }
    }
}
