//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Credito
    {
        public int Id { get; set; }
        public string Numero_Tarjeta { get; set; }
        public string Monto { get; set; }
        public string Concepto { get; set; }
        public string Restante { get; set; }
        public string Monto_disponible { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Tarjetas_Credito Tarjetas_Credito { get; set; }
    }
}
