//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Prestamos
    {
        public int Id { get; set; }
        public Nullable<int> Id_prestamo { get; set; }
        public string Monto { get; set; }
        public string Concepto { get; set; }
        public string Restante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
