//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Credito
    {
        public string Numero_tarjeta { get; set; }
        public string Balance_Cons { get; set; }
        public string Monto_Disp { get; set; }
        public string Fecha { get; set; }
    
        public virtual Tarjetas_Credito Tarjetas_Credito { get; set; }
    }
}
