//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas_Credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjetas_Credito()
        {
            this.Historial_Credito = new HashSet<Historial_Credito>();
        }
    
        public Nullable<int> Id_usuario { get; set; }
        public string Numero_Tarjeta { get; set; }
        public string Balance_Consumido { get; set; }
        public string Monto_Disponible { get; set; }
        public Nullable<int> Limite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Credito> Historial_Credito { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
